name: CI

on: [push, pull_request]

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        prefer-lowest: ['']
        php-version: ['7.4', '8.0', '8.1']
        include:
          - php-version: '7.2'
            prefer-lowest: 'prefer-lowest'

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_${{ matrix.db-type }}
        coverage: pcov

    - name: Composer install
      run: |
        if ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
          composer update --prefer-lowest --prefer-stable
        else
          composer install
        fi

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '7.4' ]]; then
          vendor/bin/phpunit --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi

    - name: Code Coverage Report
      if: matrix.php-version == '7.4'
      uses: codecov/codecov-action@v2

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        coverage: none
        tools: vimeo/psalm:4.15, phpstan:1.2

    - name: Composer Install
      run: composer require --dev cakephp/cakephp-codesniffer:^4.1

    - name: Run phpcs
      run: vendor/bin/phpcs --report=checkstyle --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/

    - name: Run psalm
      if: success() || failure()
      run: psalm --output-format=github

    - name: Run phpstan
      if: success() || failure()
      run: phpstan analyse --error-format=github
