name: CI

on: [push, pull_request]

jobs:
  testsuite:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
        dependencies: ['highest']
        include:
          - php-version: '7.2'
            dependencies: 'lowest'

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_${{ matrix.db-type }}
        coverage: pcov

    - name: Composer install
      uses: ramsey/composer-install@v2
      with:
        dependency-versions: ${{ matrix.dependencies }}

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '7.4' ]]; then
          vendor/bin/phpunit --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi

    - name: Code Coverage Report
      if: matrix.php-version == '7.4'
      uses: codecov/codecov-action@v3

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        coverage: none
        tools: vimeo/psalm:5.9, phpstan:1.10

    - name: Composer Install
      run: composer require --dev cakephp/cakephp-codesniffer:^4.1

    - name: Run phpcs
      run: vendor/bin/phpcs --report=checkstyle --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/

    - name: Run psalm
      if: success() || failure()
      run: psalm --output-format=github

    - name: Run phpstan
      if: success() || failure()
      run: phpstan analyse --error-format=github
