name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  testsuite:
    uses: cakephp/.github/.github/workflows/testsuite-without-db.yml@5.x
    secrets: inherit

  cs-stan:
    uses: ADmad/.github/.github/workflows/cs-stan.yml@master
    secrets: inherit
