name: CI

on: [push, pull_request]

jobs:
  testsuite:
    uses: cakephp/.github/.github/workflows/testsuite-without-db.yml@5.x
    secrets: inherit

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        coverage: none
        tools: vimeo/psalm:5, phpstan:1.11, cs2pr

    - name: Composer Install
      run: composer require --dev cakephp/cakephp-codesniffer:^5.0

    - name: Run phpcs
      run: vendor/bin/phpcs --report=checkstyle --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/ | cs2pr

    - name: Run psalm
      if: always()
      run: psalm --output-format=github

    - name: Run phpstan
      if: always()
      run: phpstan analyse --error-format=github
